Update package.json
Musicoin/desktop-interface pull request #4
Opened 2018-06-02 15:36 UTC by etaletai13

handle bower deps in a build step for rebuilding bower deps upon yarn add/install as dep itself.

-- this removes the need to rely on bower at all in the main app

2018-06-02 20:05 UTC, Varunram requested changes

2018-06-02 20:05 UTC, Varunram commented on package.json
> +  }
@etaletai13 you missed the usual comma here :)

2018-06-02 20:18 UTC, Varunram reviewed
Assuming this works in tandem with there there merged PR.

2018-06-02 20:19 UTC, merged

2018-06-03 20:25 UTC, Varunram commented
weirdly enough, I still find it convenient to use `bower install`, maybe its a matter of practice before I shift to `yarn` entirely..

2018-06-04 00:33 UTC, etaletai13 commented
@Varunram I really understand that, actually! I love that about yarn, because I can actually completely shift over in theory but still wrap a script around so that `bower install` ends up performing the right actions anyway. Yarn applied to things it wasn't built for is what I like to think of as crochet; because why  not push the metaphor into parable land? Anyway, this is forward moving. As I've learned, it behoves me to keep the branch around for quite a while really, just in case. I tend to be the reverse of a hoarder, and am learning to not erase the past every two minutes!! Let's keep going.